
[[constraint]]
  name = "github.com/asdine/storm"
  version = "2.1.2"

[[constraint]]
  name = "github.com/djherbis/times"
  version = "1.1.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[prune]
  go-tests = true
  unused-packages = true
