site_name: 'Varasto docs'

theme:
  name: material
  logo: assets/varasto.svg
  favicon: assets/favicon.svg # otherwise same as varasto.svg but different color

docs_dir: '.'

repo_url: https://github.com/function61/varasto/

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - footnotes
  - toc:
      permalink: true

extra_css:
  - assets/mkdocs-additional-styles.css

nav:

- index.md
- Installation: install/index.md
- Screenshots: screenshots/index.md
- Concepts, ideas & architecture: concepts-ideas-architecture/index.md
- Comparison to similar software: comparison-to-similar-software/index.md
- Performance: performance/index.md
- Ways to access your data: 
  - Overview: data-interfaces/index.md
  - Web UI: data-interfaces/web-ui/index.md
  - Varasto client: data-interfaces/client/index.md
  - Network folders: data-interfaces/network-folders/index.md
  - FUSE interface: data-interfaces/fuse/index.md
  - API (programmatic access): data-interfaces/api/index.md
- Operating:
  - SMART monitoring: using/smart-monitoring/index.md
  - Metadata backup: using/metadata-backup/index.md
  - Replication policies: using/replication-policies/index.md
  - When a disk fails: using/when-a-disk-fails/index.md
- Local / remote storage:
  - Local disk storage: storage/local-fs/index.md
  - AWS S3: storage/s3/index.md
  - Google Drive: storage/googledrive/index.md
  - Naming your volumes: storage/naming-your-volumes.md
- Types of content:
  - Files: content/generic-files/index.md
  - Photos: content/photos/index.md
  - Movies: content/movies/index.md
  - TV shows: content/tvshows/index.md
  # - Podcasts (TODO): stuff.md
- Security:
  - Encryption in Varasto: security/encryption/index.md
  - Ransomware protection: security/ransomware-protection/index.md
  - Security policy: security.md
- Developers:
  - Codebase layout: developers/codebase/index.md
  - How to build & develop: https://github.com/function61/turbobob/blob/master/docs/external-how-to-build-and-dev.md
  - Package documentation on GoDoc.org: https://godoc.org/github.com/function61/varasto
  - Server API:
    - REST endpoints: stoserver/stoservertypes/rest_endpoints.md
    - Types: stoserver/stoservertypes/types.md
    - Commands: stoserver/stoservertypes/commands.md
